### ISSUE TITLE
Recommendation Tag Management 태그 등록 최대 갯수 30개로 변경

### ISSUE THREAD

**Issue by loiu87** [akalswl14/stylebox-management#40]
검색 메인스크린의 popular tags 에 노출되는 태그 최대 수를 30개로 변경해달라고 합니다.

### 현상
management 웹 페이지의 searchtag 설정 스크린에서 최대 10개만 등록 가능

### 요청사항
등록태그 최대 30개로 변경 요청

### 체크사항
- [x] getPopularTags @ app-api

**Comment by akalswl14** [comment]
App api에는 영향이 없어 변경할 사항이 없었습니다
